INI/Controllers/Edicion/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;


namespace INI.Controllers.Edicion
{
    //[Authorize(Roles="Editor")]
    public class EditController : Controller
    {
        // GET: Edit
        public ActionResult Index()
        {
            //ViewBag.mensaje = "no es";

            //if (Roles.IsUserInRole("Editor"))
            //{
            //    ViewBag.mensaje = "Este es el editor";
            //} 
            return View();
        }
    }
}

INI/Controllers/RubroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using INI.Models.DataBase;
using dl = ClassLibrary;

namespace INI.Controllers
{
    //[Authorize(Roles = "Administrator,Maestro")]
    [Authorize]
    public class RubroController : Controller
    {
        private investicEntities db = new investicEntities();

        // GET: Rubro
        public ActionResult Index(int code=0)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ViewBag.Message = dl.ErrorCodes.ErrorCodeToString(code);
            return View(db.tblRubro.ToList());
        }

        // GET: Rubro/Details/5
        public ActionResult Details(int? id)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRubro tblRubro = db.tblRubro.Find(id);
            if (tblRubro == null)
            {
                return HttpNotFound();
            }
            return View(tblRubro);
        }

        // GET: Rubro/Create
        public ActionResult Create()
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View();
        }

        // POST: Rubro/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Rubro,Descripcion")] tblRubro tblRubro)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (ModelState.IsValid)
            {
                tblRubro variablep = db.tblRubro.SingleOrDefault(model => model.Rubro == tblRubro.Rubro);
                if (variablep == null)
                {
                    db.tblRubro.Add(tblRubro);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", new { code = 13905 });
                }
            }

            return View(tblRubro);
        }

        // GET: Rubro/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRubro tblRubro = db.tblRubro.Find(id);
            if (tblRubro == null)
            {
                return HttpNotFound();
            }
            return View(tblRubro);
        }

        // POST: Rubro/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Rubro,Descripcion")] tblRubro tblRubro)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (ModelState.IsValid)
            {
                tblRubro variablep = db.tblRubro.SingleOrDefault(model => model.Rubro == tblRubro.Rubro && model.id != tblRubro.id);
                if (variablep == null)
                {
                    db.Entry(tblRubro).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", new { code = 13905 });
                }
            }
            return View(tblRubro);
        }

        // GET: Rubro/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRubro tblRubro = db.tblRubro.Find(id);
            if (tblRubro == null)
            {
                return HttpNotFound();
            }
            return View(tblRubro);
        }

        // POST: Rubro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name) || AspNetUsersRoles.IsUserInRole("Editor", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            { 
                tblRubro tblRubro = db.tblRubro.Find(id);
                db.tblRubro.Remove(tblRubro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { code = 1390301 });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

INI/Views/Rubro/Create.cshtml
@model INI.Models.DataBase.tblRubro
@using INI.Models.DataBase
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_InvEditor.cshtml";
    var usu = User.Identity.Name;
    var rol = AspNetUsersRoles.IsUserInRole("Administrador", User.Identity.Name);
    if (!rol) { rol = AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name); }

}

<link href="~/Content/tooltipbootstrap/jquery.webui-popover.css" rel="stylesheet" />

<style>
    label, input, select {
        margin-top: 7px;
    }
</style>
<div id="ruta_miga">
    <table>
        <tr>
            <td rowspan="2">
                <ul id="img_fijos">
                    <li>
                        <a href="~/Rubro/">
                            <img src="~/images/botones_ruta_migas/btn_atras_va.png" title="Atras" />
                        </a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <img src="~/images/botones_ruta_migas/label_aqui_estoy.png" />
                    </li>
                </ul>

            </td>
        </tr>
        <tr>
            <td>
                <ul id="img_variables">
                    <li>
                        <a href="~/Home">
                            <img src="~/images/botones_ruta_migas/btn_menu_p.png" title="Menú principal" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        @if (rol == true)
                        {
                            <a href="~/Noticias">
                                <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                            </a>
                        }
                        else
                        {
                            <a href="~/Admin/Editor?nombreu=@usu">
                                <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                            </a>
                        }
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />

                    </li>
                    <li>
                        <a href="~/Rubro/">
                            <img src="~/images/botones_ruta_migas/admin/btn_rubros_pro_a.png" title="Rubro" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        <img src="~/images/botones_ruta_migas/crud/btn_crear.png" />
                    </li>
                </ul>
            </td>
        </tr>
    </table>
</div>
<br /><br /><br /><br />
<div class="panel panel-default" style="margin-top:55px;">
    <div class="panel-heading"><strong>Crear rubro</strong></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <form class="form-horizontal" style="width:500px;">

                <div class="form-group">
                    <label id="Rubroe" for="Rubro" class="col-sm-2 control-label">Nombre rubro <span style="color:red;">*</span></label>
                    <div class="col-sm-4">
                        @Html.EditorFor(m => m.Rubro, new { htmlAttributes = new { @class = "form-control", placeholder = "Escribe el nombre del rubro" } })
                        @Html.ValidationMessageFor(model => model.Rubro, String.Empty, new { @style = "color:red;!important" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-12">
                    </div>
                </div>

                <div class="form-group">
                    <label id="Descripcione" for="Descripcion" class="col-sm-2 control-label">Descripción rubro <span style="color:red;"></span></label>
                    <div class="col-sm-10">
                        @Html.EditorFor(m => m.Descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Escribe la descripción del rubro" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, String.Empty, new { @style = "color:red;!important" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="button medium primary" style="margin-top:15px;">Guardar</button>
                        @Html.ActionLink("Regresar", "Index", null, new { @class = "button medium primary", style = "margin-top:15px;" })
                    </div>
                </div>
            </form>
            @Html.ValidationSummary(true)
        }

        <div style="display:none;">
            <div id="Rubrom">
                <img src="~/images/ToolTip/p2.svg" style="float:right;margin-left:12px;" alt="" />
                <b><strong>Cuál es el nombre del rubro?</strong></b><br /><br />
                Este campo es obligatorio. Aquí debes ingresar el nombre del rubro.
            </div>
        </div>
        <div style="display:none;">
            <div id="Rubrome">
                <img src="~/images/ToolTip/p2.svg" style="float:right;margin-left:12px;" alt="" />
                <b><strong>Cuál es el nombre del rubro?</strong></b><br /><br />
                Este campo es obligatorio. Aquí debes ingresar el nombre del rubro.
            </div>
        </div>

        <div style="display:none;">
            <div id="Descripcionm">
                <img src="~/images/ToolTip/p2.svg" style="float:right;margin-left:12px;" alt="" />
                <b><strong>Cuál es la descripción del rubro?</strong></b><br /><br />
                Aquí debes ingresar una breve descripción del rubro.
            </div>
        </div>
        <div style="display:none;">
            <div id="Descripcionme">
                <img src="~/images/ToolTip/p2.svg" style="float:right;margin-left:12px;" alt="" />
                <b><strong>Cuál es la descripción del rubro?</strong></b><br /><br />
                Aquí debes ingresar una breve descripción del rubro.
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/tooltipbootstrap/jquery.webui-popover.js"></script>
    <script>
        $('#Rubro').webuiPopover({ url: '#Rubrom', trigger: 'hover', style: 'inverse', placement: 'top', width: '500px' });
        $('#Rubroe').webuiPopover({ url: '#Rubrome', trigger: 'hover', style: 'inverse', placement: 'right', width: '500px' });
        $('#Descripcion').webuiPopover({ url: '#Descripcionm', trigger: 'hover', style: 'inverse', placement: 'top', width: '500px' });
        $('#Descripcione').webuiPopover({ url: '#Descripcionme', trigger: 'hover', style: 'inverse', placement: 'right', width: '500px' });
    </script>

}


INI/Views/Rubro/Delete.cshtml
@model INI.Models.DataBase.tblRubro
@using INI.Models.DataBase
@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_InvEditor.cshtml";
    var usu = User.Identity.Name;
    var rol = AspNetUsersRoles.IsUserInRole("Administrador", User.Identity.Name);
    if (!rol) { rol = AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name); }

}
<div id="ruta_miga">
    <table>
        <tr>
            <td rowspan="2">
                <ul id="img_fijos">
                    <li>
                        <a href="~/Rubro/">
                            <img src="~/images/botones_ruta_migas/btn_atras_va.png" title="Atras" />
                        </a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <img src="~/images/botones_ruta_migas/label_aqui_estoy.png" />
                    </li>
                </ul>

            </td>
        </tr>
        <tr>
            <td>
                <ul id="img_variables">
                    <li>
                        <a href="~/Home">
                            <img src="~/images/botones_ruta_migas/btn_menu_p.png" title="Menú principal" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        @if (rol == true)
                        {
                            <a href="~/Noticias">
                                <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                            </a>
                        }
                        else
                        {
                            <a href="~/Admin/Editor?nombreu=@usu">
                                <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                            </a>
                        }
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />

                    </li>
                    <li>
                        <a href="~/Rubro/">
                            <img src="~/images/botones_ruta_migas/admin/btn_rubros_pro_a.png" title="Rubro" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        <img src="~/images/botones_ruta_migas/crud/btn_eliminar.png" />
                    </li>
                </ul>
            </td>
        </tr>
    </table>
</div>
<br /><br /><br /><br />
<div class="panel panel-default" style="margin-top:55px;">
    <div class="panel-heading"><strong>Eliminar rubro</strong></div>
    <div class="panel-body">
        <p>¿Estás seguro que quieres eliminar la siguiente información?</p>
        <div class="media-body container well">
            <dl class="dl-horizontal">
                <dt style="padding-bottom: 5px; width: 200px;">@Html.DisplayNameFor(model => model.Rubro):&nbsp&nbsp</dt>
                <dd>@Html.DisplayFor(model => model.Rubro)</dd>

                <dt style="padding-bottom: 5px; width: 200px;">@Html.DisplayNameFor(model => model.Descripcion):&nbsp&nbsp</dt>
                <dd>@Html.DisplayFor(model => model.Descripcion)</dd>

                <dt style="padding-bottom:2px;">&nbsp&nbsp</dt>
                <dd>&nbsp&nbsp</dd>

                <dt style="padding-bottom:5px;">&nbsp&nbsp</dt>
                <dd>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Eliminar" class="button medium primary" />
                        @Html.ActionLink("Regresar", "Index", null, new { @class = "button medium primary" })
                    }

                </dd>
            </dl>
        </div>
    </div>
</div>

INI/Views/Rubro/Details.cshtml
@model INI.Models.DataBase.tblRubro
@using INI.Models.DataBase
@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_InvEditor.cshtml";
    var usu = User.Identity.Name;
    var rol = AspNetUsersRoles.IsUserInRole("Administrador", User.Identity.Name);
    if (!rol) { rol = AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name); }

}
<div id="ruta_miga">
    <table>
        <tr>
            <td rowspan="2">
                <ul id="img_fijos">
                    <li>
                        <a href="~/Rubro/">
                            <img src="~/images/botones_ruta_migas/btn_atras_va.png" title="Atras" />
                        </a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <img src="~/images/botones_ruta_migas/label_aqui_estoy.png" />
                    </li>
                </ul>

            </td>
        </tr>
        <tr>
            <td>
                <ul id="img_variables">
                    <li>
                        <a href="~/Home">
                            <img src="~/images/botones_ruta_migas/btn_menu_p.png" title="Menú principal" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        @if (rol == true)
                        {
                            <a href="~/Noticias">
                                <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                            </a>
                        }
                        else
                        {
                            <a href="~/Admin/Editor?nombreu=@usu">
                                <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                            </a>
                        }
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />

                    </li>
                    <li>
                        <a href="~/Rubro/">
                            <img src="~/images/botones_ruta_migas/admin/btn_rubros_pro_a.png" title="Rubro" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        <img src="~/images/botones_ruta_migas/crud/btn_detalle.png" />
                    </li>
                </ul>
            </td>
        </tr>
    </table>
</div>
<br /><br /><br /><br />
<h2>Detalle</h2>

<div>
    <h4>Rubro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rubro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rubro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Atrás", "Index")
</p>

INI/Views/Rubro/Index.cshtml
@model IEnumerable<INI.Models.DataBase.tblRubro>
@using INI.Models.DataBase
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_InvEditor.cshtml";
    var usu = User.Identity.Name;
    var rol = AspNetUsersRoles.IsUserInRole("Administrador", User.Identity.Name);
    if (!rol) { rol = AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name); }

}
                      <div id="ruta_miga">
                          <table>
                              <tr>
                                  <td rowspan="2">
                                      <ul id="img_fijos">
                                          <li>
                                              @*<a href="~/PanelAdministrativo">*@
                                              <a href="javascript:history.back(1)">
                                                  <img src="~/images/botones_ruta_migas/btn_atras_va.png" title="Atras" />
                                              </a>
                                          </li>
                                      </ul>
                                  </td>
                                  <td>
                                      <ul>
                                          <li>
                                              <img src="~/images/botones_ruta_migas/label_aqui_estoy.png" />
                                          </li>
                                      </ul>

                                  </td>
                              </tr>
                              <tr>
                                  <td>
                                      <ul id="img_variables">
                                          <li>
                                              <a href="~/Home">
                                                  <img src="~/images/botones_ruta_migas/btn_menu_p.png" title="Menú principal" />
                                              </a>
                                          </li>
                                          <li>
                                              <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                                          </li>
                                          <li>
                                              @if (rol == true)
                                              {
                                                  <a href="~/Noticias">
                                                      <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                                                  </a>
                                              }
                                              else
                                              {
                                                  <a href="~/Admin/Editor?nombreu=@usu">
                                                      <img src="~/images/botones_ruta_migas/editor/btn_edit_a.png" title="Editor" />
                                                  </a>
                                              }
                                          </li>
                                          <li>
                                              <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                                          </li>
                                          <li>
                                              <img src="~/images/botones_ruta_migas/admin/btn_rubros_pro_v.png" title="Rubro" />
                                          </li>
                                      </ul>
                                  </td>
                              </tr>
                          </table>
                      </div>
                      <br /><br /><br /><br /><br /><br />
<h2 style="font-family:Chewy;">Rubro</h2>


<p>
    @Html.ActionLink("Nuevo elemento de lista", "Create", "", new { @class = "button large primary" })
</p>
<table id="Tabla_1" class="table striped hover" style="width:100%">
    <thead>
        <tr>
            <th>
                Rubro
            </th>
            <th>Acciones</th>
        </tr>
    </thead>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Rubro)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
@section Scripts{
    <script src="~/Scripts/DataTables-1.10.4/jquery.dataTables.js"></script>
    <script>
            $(function () {
                $('#Tabla_1').dataTable({
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sUrl": "../../Lang/es-CO.txt"
                    }
                });


                $(function () {
                    $('#Tabla_2').dataTable({
                        "sPaginationType": "full_numbers",
                        "oLanguage": {
                            "sUrl": "../../Lang/es-CO.txt"
                        }
                    });

                });
            });

    </script>
}