INI/Models/Admin/LogAcceso.cs
using INI.Models.DataBase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace INI.Models.Admin
{
    public class LogAcceso 
    {       

        
        public string Rol { get; set; }
        
        public string Usuario { get; set; }

        public string Nombre { get; set; }


        public string IP { get; set; }

        
        public string Latitud { get; set; }

        
        public string Longitud { get; set; }

        
        public string Altitud { get; set; }        

        
        public Nullable<System.DateTime> FechaInicioSesion { get; set; }

        
        public Nullable<System.DateTime> FechaCierreSesion { get; set; }
        public String Image { get; set; }
    }
}

INI/Controllers/Administracion/LogAccesoController.cs
using INI.Models.DataBase;
using INI.Models.DataTableAjaxModels;
using INI.Models.DataTableAjaxModels.Binder;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Linq.Dynamic;
using INI.Extensions.Controllers;
using INI.Models.RangeFechas;
using INI.Extensions.ActionResults;
using INI.Models.Admin;
using System.Net;
using ExcelReporLibrary;
using System.Collections.Generic;
using ExcelReporLibrary.Models;
using INI.Models.Mymodels;
using Newtonsoft.Json;

namespace INI.Controllers.Administracion
{
    //[Authorize(Roles = "Administrator")]
    [Authorize]
    public class LogAccesoController : NewtomSofController
    {
        private investicEntities db = new investicEntities();

        // GET: LogAcceso
        public ActionResult Index()
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var statelog = db.tblConfiguration.Where(m => m.operation == 1 && m.element == 1).OrderByDescending(m => m.DateOperation).Select(m => m.IsEnabled).FirstOrDefault();
            ViewBag.statelog = statelog;

            return View();
        }

        public ActionResult Navigation(int id = 0)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var navigation = db.tblLogAcceso.Where(m => m.id == id).FirstOrDefault();
            List<NavegationModel> navigationobj= JsonConvert.DeserializeObject<List<NavegationModel>>(navigation.Navegacion).OrderByDescending(m=>m.ImputDateUrl).ToList();
            String username=db.AspNetUsers.Where(model => model.UserName == navigation.Usuario).Select(model => new { Name = model.Name + " " + model.SureName }).Take(1).FirstOrDefault().Name;
            NavigationLog nl = new NavigationLog() { id = navigation.id, Rol = navigation.Rol, Usuario = username, IP = navigation.IP, Latitud = navigation.Latitud, Longitud = navigation.Longitud, Altitud = navigation.Longitud, FechaInicioSesion = navigation.FechaInicioSesion, FechaCierreSesion = navigation.FechaCierreSesion, navigations = navigationobj };
            return View(nl);
        }

        public ActionResult ChangeStateLog(bool state)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            db.tblConfiguration.Add(new tblConfiguration() { DateOperation = System.DateTime.Now, element = 1, operation = 1, IsEnabled = state });
            db.SaveChanges();
            String rta = "Ok";
            return Json(rta, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetReport([Bind(Include = "StartDate,EndDate,IsRole,IsAdvancedSearch,criterion,ReportType")]ReportModel model)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (ModelState.IsValid)
            {
                switch (model.ReportType)
                {
                    case 1:
                        string filePath = Server.MapPath("/ExcelTemplates/ReportLog.xlsx");
                        ExcelReportModel rm = new ExcelReportModel();
                        //List<>

                        var datos = db.tblLogAcceso.Where(m => m.FechaInicioSesion >= model.StartDate && m.FechaInicioSesion <= model.EndDate).OrderByDescending(m => m.FechaInicioSesion).
                            Select(m =>
                            new LogRow() {
                                Rol = m.Rol,
                                Usuario = m.Usuario ,
                                Nombre= db.AspNetUsers.Where(model2 => model2.UserName == m.Usuario).Select(model2 => new { Name = model2.Name + " " + model2.SureName }).Take(1).FirstOrDefault().Name,
                                Altitud = m.Altitud,
                                Latitud = m.Latitud,
                                IP = m.IP,
                                FechaCierreSesion = m.FechaCierreSesion.Value,
                                FechaInicioSesion = m.FechaInicioSesion.Value
                            });


                        if (model.IsAdvancedSearch)
                        {
                            if (model.IsRole)
                            {
                                datos = db.tblLogAcceso.Where(m => m.FechaInicioSesion >= model.StartDate && m.FechaInicioSesion <= model.EndDate && m.Rol.Contains(model.criterion)).OrderByDescending(m => m.FechaInicioSesion).
                                    Select(m => 
                                    new LogRow() {
                                        Rol = m.Rol,
                                        Usuario = m.Usuario,
                                        Nombre = db.AspNetUsers.Where(model2 => model2.UserName == m.Usuario).Select(model2 => new { Name = model2.Name + " " + model2.SureName }).Take(1).FirstOrDefault().Name,
                                        Altitud = m.Altitud,
                                        Latitud = m.Latitud,
                                        IP = m.IP,
                                        FechaCierreSesion = m.FechaCierreSesion.Value,
                                        FechaInicioSesion = m.FechaInicioSesion.Value
                                    });
                            }
                            else
                            {
                                datos = db.tblLogAcceso.Where(m => m.FechaInicioSesion >= model.StartDate && m.FechaInicioSesion <= model.EndDate ).OrderByDescending(m => m.FechaInicioSesion).
                                    Select(m => 
                                    new LogRow() {
                                        Rol = m.Rol,
                                        Usuario = m.Usuario,
                                        Nombre = db.AspNetUsers.Where(model2 => model2.UserName == m.Usuario).Select(model2 => new { Name = model2.Name + " " + model2.SureName }).Take(1).FirstOrDefault().Name,
                                        Altitud = m.Altitud,
                                        Latitud = m.Latitud,
                                        IP = m.IP,
                                        FechaCierreSesion = m.FechaCierreSesion.Value,
                                        FechaInicioSesion = m.FechaInicioSesion.Value
                                    }).Where(m=>m.Nombre.Contains(model.criterion));
                            }
                        }
                        rm.LstLog = datos.ToList();
                        return new ExcelResult(ExcelReport.HistoricReport(filePath, rm), "Report " + System.DateTime.Now);
                    //return null;
                    case 2:
                        return new PDFResult(INI.LogReport.Reporte(model), "reporteLogAcceso");
                    default:
                        return RedirectToAction("Index");

                }

            }
            else return RedirectToAction("Index");
        }


        
        public ActionResult GetNavigateReport(int id, int reporttype=1)
        {
            switch (reporttype)
            {
                case 1:
                    string filePath = Server.MapPath("/ExcelTemplates/Navigate.xlsx");
                    var navigation = db.tblLogAcceso.Where(m => m.id == id).FirstOrDefault();
                    
                    List<NavegationModel_> navigationobj = JsonConvert.DeserializeObject<List<NavegationModel_>>(navigation.Navegacion).OrderByDescending(m => m.ImputDateUrl).ToList();
                    NavigationLog_ nl = new NavigationLog_() { id = navigation.id, Rol = navigation.Rol, Usuario = AspNetUsers.GetName(navigation.Usuario), IP = navigation.IP, Latitud = navigation.Latitud, Longitud = navigation.Longitud, Altitud = navigation.Longitud, FechaInicioSesion = navigation.FechaInicioSesion, FechaCierreSesion = navigation.FechaCierreSesion, navigations = navigationobj };
                    return new ExcelResult(ExcelReport.HistoricNavigateReport(filePath, nl), "Report " + System.DateTime.Now);
                case 2:
                    return null;
                default:
                    return null;
                    
            }

            
        }
        



        [HttpPost]
        public ActionResult getLogAcceso(String Dates, [ModelBinder(typeof(RqDatatableModelBinder))]RequestModel requestModel)
        {
            if (!(AspNetUsersRoles.IsUserInRole("Administrator", User.Identity.Name))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ResponseModel<LogAcceso> responseModel = new ResponseModel<LogAcceso>();
            Type dat = typeof(LogAcceso);

            //---Parametros de control
            string conditions = "";
            string orderbyparameters = "";

            string[] DatesString = Dates.Split('-');

            DateTime logenddate = DateTime.Now;
            DateTime logstartdate = DateTime.Now.AddMonths(-1);
            DateTime nowdate = DateTime.Now;

            if (DatesString.Length == 2) {
                string[] datestartparts = DatesString[0].Split('/');
                string[] datendparts = DatesString[1].Split('/');

                try
                {
                    logstartdate = new DateTime(int.Parse(datestartparts[2]),int.Parse(datestartparts[1]),int.Parse(datestartparts[0]),nowdate.Hour,nowdate.Minute,nowdate.Second);

INI/Views/LogAcceso/Index.cshtml
@model IEnumerable<INI.Models.DataBase.tblLogAcceso>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_InvAdministrator.cshtml";
    var startdate = System.DateTime.Now.AddMonths(-1);
    var enddate = System.DateTime.Now;

    string sd = startdate.Year + "/" + startdate.Month + "/" + startdate.Day;
    string ed = enddate.Year + "/" + enddate.Month + "/" + enddate.Day;
    string ed2 = enddate.Year + "/" + enddate.Month + "/" + (enddate.Day+1);
    var msjlog = "";
    var ischecked = "checked";
    bool statelog = ViewBag.statelog;
    if (statelog)
    {
        msjlog = "Log de acceso habilitado";
    }
    else
    {
        msjlog = "Log de acceso deshabilitado";
        ischecked = "";
    }

}
<div id="ruta_miga">
    <table>
        <tr>
            <td rowspan="2">
                <ul id="img_fijos">
                    <li>
                        @*<a href="~/PanelAdministrativo">*@
                        <a href="javascript:history.back(1)">
                            <img src="~/images/botones_ruta_migas/btn_atras_va.png" title="Atras" />
                        </a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <img src="~/images/botones_ruta_migas/label_aqui_estoy.png" />
                    </li>
                </ul>

            </td>
        </tr>
        <tr>
            <td>
                <ul id="img_variables">
                    <li>
                        <a href="~/Home">
                            <img src="~/images/botones_ruta_migas/btn_menu_p.png" title="Menú principal" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        @*<a href="~/PanelAdministrativo">*@
                        <a href="~/Administrator">
                            <img src="~/images/botones_ruta_migas/admin/btn_admin_a.png" title="Administrador" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        <img src="~/images/botones_ruta_migas/admin/btn_log_acces.png" title="Log de acceso" />
                    </li>
                </ul>
            </td>
        </tr>
    </table>
</div>
<br /><br /><br /><br /><br /><br />
<div class="grid">
    <div class="row">
        <div class="span4">
            <button id="btn_generarreporte" class="button large primary" style="cursor:pointer">Generar reporte</button>
        </div>
        <div class="span2">
            <strong id="lbl_enabledlog" >@msjlog</strong>
        </div>
        <div class="span2">
            <div class="input-control switch" id="chk_enablelog" style="cursor:pointer">
                <label>
                    <input id="chk_logacceso" type="checkbox"  @ischecked/>
                    <span class="check"></span>
                </label>
            </div>
        </div>
        <div class="span4"></div>
    </div>
</div>

<div id="div_reporte" class="panel" style="display:none">
    <div class="panel-header">
        Reporte
    </div>
    <div class="panel-content" style="padding-left:35px">
        @Html.Partial("~/Views/Shared/_LogAccesoReporte.cshtml", new INI.Models.RangeFechas.DateRange())
    </div>

    
    @*<a id="btn_descargarreporte" class="button large bg-green" >Descargar</a>*@

</div>
<div class="bg-white" style="border-radius:5px;padding:5px;margin:5px;">
    Los valores de la imágen <img src="~/images/true.png" /> corresponden a los usuarios que no han dado clic en <strong>Cerrar Sesión</strong> <br />
    La imágen <img src="~/images/false.png" /> corresponde a los usuarios que <strong> SI</strong> han dado clic en <strong>Cerrar Sesión</strong>
</div>

<div class="row">
    <div class="span2">
        <label id="_logfechainicial"><strong style="cursor:pointer">Fecha inicial</strong></label>
    </div>
    <div class="span4 input-control text" data-role="datepicker" data-format="dd/mm/yyyy" data-locale="es" data-effect="slide" data-position="top" data-date="@sd">
        @*@Html.TextBoxFor(m => m.StartDate, "{0:dd/MM/yyyy}", new { @type = "text" })*@
        <input id="LogStartDate" type="text" />
        <button class="btn btn-date" type="button"></button>
        @*@Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })*@
    </div>
</div>
<div class="row">
    <div class="span2">
        <label id="_logfechafinal"><strong style="cursor:pointer">Fecha final</strong></label>
    </div>
    <div class="span4 input-control text" data-role="datepicker" data-format="dd/mm/yyyy" data-locale="es" data-effect="slide" data-position="top" data-date="@ed">
        @*@Html.TextBoxFor(m => m.EndDate, "{0:dd/MM/yyyy}", new { @type = "text" })*@
        <input id="LogEndDate" type="text" />
        <button class="btn btn-date" type="button"></button>
        <span id="logval_enddate" style="display:none;color:red">La fecha final es menor que la fecha inicial</span>
        @*@Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })*@
    </div>
</div>

<table class="table" id="tbl_logAcceso">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                Nombre
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Altitud)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.FechaInicioSesion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaCierreSesion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
@section scripts{
    @*<link href="~/Content/tooltip.css" rel="stylesheet" />
    <script src="~/Scripts/tooltip.js"></script>*@
    <script src="~/Scripts/moment.js"></script>
    <script>

        $(function () {
            $("#btn_test").click(function () {
                alert($("#LogStartDate").val());
            });
            $("form").submit(function () {
                var startdate=$("#StartDate").val();
                var enddate = $("#EndDate").val();

                var sdate = startdate.split('/');
                var edate = enddate.split('/');

                var s_date = new Date(parseInt(sdate[2]), parseInt(sdate[1])-1, parseInt(sdate[0]), 0, 0, 0);
                var e_date = new Date(parseInt(edate[2]), parseInt(edate[1])-1, parseInt(edate[0]), 0, 0, 0);
                

                if (s_date > e_date) {
                    $("#val_enddate").show();
                    return false;
                }
                else {
                    $("#val_enddate").hide();
                }
                
                
            });

            $("#chk_isAR").click(function () {
                if ($(this).is(':checked')) {
                    $("#grp_rd_ar").show();
                    $("#txt_repo").show();
                    $("#IsAdvancedSearch").val(true);
                }
                else {
                    $("#grp_rd_ar").hide();
                    $("#txt_repo").hide();
                    $("#IsAdvancedSearch").val(false);
                }
            });
            
            

            $("#chk_logacceso").click(function () {
                if ($(this).is(':checked')) {
                    $("#lbl_enabledlog").html("Log de acceso habilitado");
                    $.getJSON("@Url.Action("ChangeStateLog", "LogAcceso")",{state:true}, function(){
                        //var not = $.Notify.show('El log se ha habilitado');
                        AlertMessage('El log de acceso cambió');
                    });
                }
                else {
                    $("#lbl_enabledlog").html("Log de acceso deshabilitado");
                    $.getJSON("@Url.Action("ChangeStateLog", "LogAcceso")",{state:false}, function(){
                        //var not = $.Notify.show("El log se ha deshabilitado");
                        AlertMessage('El log de acceso cambió');
                    });
                }
            });


            $("#rdreportto1").click(function () {
                $("#IsRole").val(true);
            });
            $("#rdreportto2").click(function () {
                $("#IsRole").val(false);
            });

            $("#btn_generarreporte").click(function () {

                $("#div_reporte").fadeToggle();
            });
            $("#btn_generarreporte").click(function () {
            });

         
            $('#tbl_logAcceso').DataTable({
                "processing": true,
                "serverSide": true,
                "oLanguage": {
                    "sUrl": "../../Lang/es-CO.txt"
                },
                "ajax": {
                    "url": "/LogAcceso/getLogAcceso?Dates=" + $("#LogStartDate").val() + "-" + $("#LogEndDate").val(),
                    "type": "POST"
                },
                "columns": [
                    { "data": "Rol" },
                    { "data": "Usuario" },
                    { "data": "Nombre" },
                    { "data": "IP" },
                    { "data": "Latitud" },
                    { "data": "Longitud" },
                    { "data": "Altitud" },                    
                    { "data": "FechaInicioSesion" },
                    { "data": "FechaCierreSesion" },
                    { "data": "Image" }

                ],
                "order": [[7, 'desc']]


            });

            $('#tbl_logAcceso tbody').on('load', 'td.details-control', function () {
                var tr = $(this).closest('tr');
                var row = table.row(tr);

                console.log(tr);
            });

            $("#rd_excel").click(function () {
                $("#ReportType").val(1);
            });

            $("#rd_pdf").click(function () {
                $("#ReportType").val(2);
            });      

        });

        $('#lbl_report_type').webuiPopover({ url: '#report_type', trigger: 'hover', style: 'inverse', placement: 'right', width: '300px' });
        $('#btn_generarreporte').webuiPopover({ url: '#reportlog', trigger: 'hover', style: 'inverse', placement: 'right', width: '300px' });        
        $('#chk_enablelog').webuiPopover({ url: '#shwichreport', trigger: 'hover', style: 'inverse', placement: 'right', width: '400px' });
        $('#_fechainicial').webuiPopover({ url: '#fechainicial', trigger: 'hover', style: 'inverse', placement: 'right', width: '300px' });
        $('#StartDate').webuiPopover({ url: '#fechainicial2', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });
        $('#_fechafinal').webuiPopover({ url: '#fechafinal1', trigger: 'hover', style: 'inverse', placement: 'right', width: '300px' });
        $('#EndDate').webuiPopover({ url: '#fechafinal2', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });        
        $('#chk_repadvance').webuiPopover({ url: '#checkreportavance', trigger: 'hover', style: 'inverse', placement: 'right', width: '300px' });
        $('#chk_roladvance').webuiPopover({ url: '#roles_log', trigger: 'hover', style: 'inverse', placement: 'top', width: '270px' });
        $('#chk_useradvance').webuiPopover({ url: '#usuarioid', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });
        $('#criterio_report').webuiPopover({ url: '#criterios', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });
        $('#btn_downloadreport').webuiPopover({ url: '#downloadreport', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });

        $('#LogStartDate').webuiPopover({ url: '#fechainicialgeneral', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });
        $('#LogEndDate').webuiPopover({ url: '#fechafinageneral', trigger: 'hover', style: 'inverse', placement: 'top', width: '300px' });

        
    </script>

}
<div style="display:none;">
    <div id="fechainicialgeneral">
        <img src="~/images/ToolTip/p4.svg" style="float:right;margin-left:12px;" alt="" />
        <b><strong>Fecha inicial</strong></b><br /><br />
        En este espacio selecciona desde qué fecha se quiere generar la búsqueda.
    </div>
</div>
<div style="display:none;">
    <div id="fechafinageneral">
        <img src="~/images/ToolTip/p4.svg" style="float:right;margin-left:12px;" alt="" />
        <b><strong>Fecha final</strong></b><br /><br />
        En este espacio selecciona hasta qué fecha se quiere generar la búsqueda.
    </div>
</div>

INI/Views/LogAcceso/Navigation.cshtml
@model INI.Models.Mymodels.NavigationLog

@{
    Layout = "~/Views/Shared/_InvAdministrator.cshtml";
}
<div id="ruta_miga">
    <table>
        <tr>
            <td rowspan="2">
                <ul id="img_fijos">
                    <li>
                        <a href="~/LogAcceso">
                            <img src="~/images/botones_ruta_migas/btn_atras_va.png" title="Atras" />
                        </a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <img src="~/images/botones_ruta_migas/label_aqui_estoy.png" />
                    </li>
                </ul>

            </td>
        </tr>
        <tr>
            <td>
                <ul id="img_variables">
                    <li>
                        <a href="~/Home">
                            <img src="~/images/botones_ruta_migas/btn_menu_p.png" title="Menú principal" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        @*<a href="~/PanelAdministrativo">*@
                        <a href="~/Administrator">
                            <img src="~/images/botones_ruta_migas/admin/btn_admin_a.png" title="Administrador" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        <a href="~/LogAcceso">
                            <img src="~/images/botones_ruta_migas/admin/btn_log_acces_a.png" title="Log de acceso" />
                        </a>
                    </li>
                    <li>
                        <img id="img_mano" src="~/images/botones_ruta_migas/img_mano.png" />
                    </li>
                    <li>
                        <img src="~/images/botones_ruta_migas/admin/btn_navegacion.png" title="" />
                    </li>
                   
                </ul>
            </td>
        </tr>
    </table>
</div>
<br /><br /><br /><br /><br /><br />
<div class="panel" data-role="panel">
    <div class="panel-header">
        Log
    </div>
    <div class="panel-content">
        <div class="grid" style="margin-left:20px">
            <div class="row">
                <div class="span2">
                    <strong>Rol</strong>
                </div>
                <div class="span4">
                    @Model.Rol
                </div>
                <div class="span2">
                    <strong>Usuario</strong>
                </div>
                <div class="span4">
                    @Model.Usuario
                </div>
            </div>
            <div class="row">
                <div class="span2">
                    <strong>IP</strong>
                </div>
                <div class="span4">
                    @Model.IP
                </div>
                <div class="span2">
                    <strong>Coordenadas</strong>
                </div>
                <div class="span4">
                    @String.Format("{0},{1}", Model.Latitud, Model.Longitud)
                </div>
            </div>
            <div class="row">
                <div class="span2">
                    <strong>Inicio sesión</strong>
                </div>
                <div class="span4">
                    @Model.FechaInicioSesion
                </div>
                <div class="span2">
                    <strong>Cierre sesión</strong>
                </div>
                <div class="span4">
                    @Model.FechaCierreSesion
                </div>
            </div>
        </div>
    </div>
</div>
<a href="@Url.Action("GetNavigateReport","LogAcceso", new {id= Model.id})" class="button large primary">Descargar</a>

<table id="tbl_navigation" class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Rol
            </th>
            <th>
                IP
            </th>
            <th>
                Fecha
            </th>

            <th>
                URL
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.navigations)
        {
            <tr>
                <td>
                    @Model.Usuario
                </td>
                <td>
                    @Model.Rol
                </td>
                <td>
                    @Model.IP
                </td>
                <td>
                    @item.ImputDateUrl
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Url)
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#tbl_navigation').DataTable({
                "oLanguage": {
                    "sUrl": "../../Lang/es-CO.txt"
                },
            });

        });
    </script>
}
