MAI/Controllers/MAI/ProyectosInvestigacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MAI.Models.DataBase;

namespace MAI.Controllers.Investigacion
{
    [Authorize]
    public class ProyectosInvestigacionController : Controller
    {
        private investicEntities db = new investicEntities();

        public ActionResult Index(long? id)//recibe el id del grupo de investigacion
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGruposInvestigacion miGrupo = db.tblGruposInvestigacion.Find(id);
            if (miGrupo == null)
            {
                return HttpNotFound();
            }
            return View(miGrupo);
        }

        public ActionResult Proyectos(long? id)//recibe el id del grupo de investigacion
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGruposInvestigacion miGrupo = db.tblGruposInvestigacion.Find(id);
            if (miGrupo == null)
            {
                return HttpNotFound();
            }

            ViewBag.tblGruposInvestigacion_ID = id;
            return View(miGrupo);
        }

        public ActionResult CrearProyecto(long? id) //recibe el id del grupo de Investigacion
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGruposInvestigacion miGrupo = db.tblGruposInvestigacion.Find(id);
            if (miGrupo == null)
            {
                return HttpNotFound();
            }

            ViewBag.tblGruposInvestigacion_ID = id;
            return View(miGrupo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearProyecto([Bind(Include = "tblProyectosInvestigacion_ID,tblGruposInvestigacion_ID,proyInv_nombreProyecto,proInv_fechaCreacion,proInv_fechaUltimaModificacion")] tblProyectosInvestigacion tblProyectosInvestigacion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!tblProyectosInvestigacion.proyInv_nombreProyecto.Equals(null))
                    {
                        tblProyectosInvestigacion.tblEstado_ID = 1; //Estado Activo
                        tblProyectosInvestigacion.proyInv_fechaCreacion = DateTime.Now;
                        tblProyectosInvestigacion.proyInv_fechaUltimaModificacion = DateTime.Now;
                        //Agregar Tablas al Proyecto
                        addTablasProyecto(tblProyectosInvestigacion);
                        //Agregar Tablas de Revision
                        //addTablasRevProyecto(tblProyectosInvestigacion);
                        //-------------Revision
                        tblProyectosInvestigacion_Rev rev = evaluacionProyecto(tblProyectosInvestigacion);
                        tblProyectosInvestigacion_Rev rev1 = evaluacionProyecto(tblProyectosInvestigacion);
                        tblProyectosInvestigacion_Rev rev2 = evaluacionProyecto(tblProyectosInvestigacion);
                        tblProyectosInvestigacion_Rev rev3 = evaluacionProyecto(tblProyectosInvestigacion);

                        tblProyectosInvestigacion.tblProyectosInvestigacion_Rev = rev;
                        tblProyectosInvestigacion.tblProyectosInvestigacion_Rev1 = rev1;
                        tblProyectosInvestigacion.tblProyectosInvestigacion_Rev2 = rev2;
                        tblProyectosInvestigacion.tblProyectosInvestigacion_Rev3 = rev3;

                        //--------------------- 


                        db.tblProyectosInvestigacion.Add(tblProyectosInvestigacion);
                        tblGruposInvestigacion miGrupoInv = db.tblGruposInvestigacion.Find(tblProyectosInvestigacion.tblGruposInvestigacion_ID);
                        miGrupoInv.gruInv_proyectos = miGrupoInv.gruInv_proyectos + 1;
                        db.Entry(miGrupoInv).State = EntityState.Modified;
                        db.SaveChanges();

                        //Guardar revisions
                        rev.tblProyectosInvestigacion_ID = tblProyectosInvestigacion.tblProyectosInvestigacion_ID;
                        rev1.tblProyectosInvestigacion_ID = tblProyectosInvestigacion.tblProyectosInvestigacion_ID;
                        rev2.tblProyectosInvestigacion_ID = tblProyectosInvestigacion.tblProyectosInvestigacion_ID;
                        rev3.tblProyectosInvestigacion_ID = tblProyectosInvestigacion.tblProyectosInvestigacion_ID;

                        db.Entry(rev).State = EntityState.Modified;
                        db.Entry(rev1).State = EntityState.Modified;
                        db.Entry(rev2).State = EntityState.Modified;
                        db.Entry(rev3).State = EntityState.Modified;
                        db.SaveChanges();
                        
                        return RedirectToAction("Proyectos", new { id = tblProyectosInvestigacion.tblGruposInvestigacion_ID });
                    }
                }
                catch (Exception)
                {
                    //throw;
                    return RedirectToAction("Proyectos", new { id = tblProyectosInvestigacion.tblGruposInvestigacion_ID });
                }
            }
            tblGruposInvestigacion miGrupo = db.tblGruposInvestigacion.Find(tblProyectosInvestigacion.tblGruposInvestigacion_ID);
            return View(miGrupo);
        }

        private void addTablasProyecto(tblProyectosInvestigacion tblProyectosInvestigacion)
        {
            //tabla presentacion proyecto
            tblPresentacionProyecto presentacionProy = new tblPresentacionProyecto();
            presentacionProy.preProy_tituloProy = tblProyectosInvestigacion.proyInv_nombreProyecto;
            db.tblPresentacionProyecto.Add(presentacionProy);
            //tabla problema de investigacion
            tblProblemaInvestigacionProy problemaProy = new tblProblemaInvestigacionProy();
            db.tblProblemaInvestigacionProy.Add(problemaProy);
            //tabla marco de referencia
            tblMarcoReferenciaProy marcoProy = new tblMarcoReferenciaProy();
            db.tblMarcoReferenciaProy.Add(marcoProy);
            //tabla metodo
            tblMetodoProy metodoProy = new tblMetodoProy();
            db.tblMetodoProy.Add(metodoProy);
            //tabla caracteristicas
            tblCaracteristicasProy caractProy = new tblCaracteristicasProy();
            db.tblCaracteristicasProy.Add(caractProy);
            //tabla cronograma
            tblCronogramaProy cronogramaProy = new tblCronogramaProy();
            db.tblCronogramaProy.Add(cronogramaProy);
            //tabla presupuesto
            tblPresupuestoProy presupuestoProy = new tblPresupuestoProy();
            db.tblPresupuestoProy.Add(presupuestoProy);
            //tabla referencias
            tblReferenciasProy referenciasProy = new tblReferenciasProy();
            db.tblReferenciasProy.Add(referenciasProy);

            db.SaveChanges();

            tblProyectosInvestigacion.tblPresentacionProyecto = presentacionProy;
            tblProyectosInvestigacion.tblProblemaInvestigacionProy = problemaProy;
            tblProyectosInvestigacion.tblMarcoReferenciaProy = marcoProy;
            tblProyectosInvestigacion.tblMetodoProy = metodoProy;
            tblProyectosInvestigacion.tblCaracteristicasProy = caractProy;
            tblProyectosInvestigacion.tblCronogramaProy = cronogramaProy;
            tblProyectosInvestigacion.tblPresupuestoProy = presupuestoProy;
            tblProyectosInvestigacion.tblReferenciasProy = referenciasProy;

        }

        private void addTablasRevProyecto(tblProyectosInvestigacion tblProyectosInvestigacion)
        {
            tblProyectosInvestigacion.tblProyectosInvestigacion_Rev = evaluacionProyecto(tblProyectosInvestigacion);
            tblProyectosInvestigacion.tblProyectosInvestigacion_Rev1 = evaluacionProyecto(tblProyectosInvestigacion);
            tblProyectosInvestigacion.tblProyectosInvestigacion_Rev2 = evaluacionProyecto(tblProyectosInvestigacion);
            tblProyectosInvestigacion.tblProyectosInvestigacion_Rev3 = evaluacionProyecto(tblProyectosInvestigacion);

            //tblProyectosInvestigacion.tblEvaluacionProyColciencias_ID = evaluacionProyecto(tblProyectosInvestigacion);
            //tblProyectosInvestigacion.tblEvaluacionProyInvestic_ID = evaluacionProyecto(tblProyectosInvestigacion);
            //tblProyectosInvestigacion.tblEvaluacionProyEvaluador1_ID = evaluacionProyecto(tblProyectosInvestigacion);
            //tblProyectosInvestigacion.tblEvaluacionProyEvaluador2_ID = evaluacionProyecto(tblProyectosInvestigacion);
        }

        private tblProyectosInvestigacion_Rev evaluacionProyecto(tblProyectosInvestigacion tblProyectosInvestigacion)
        {
            //Tablas de Revision
            tblPresentacionProyecto_Rev revPresentacionProyecto = new tblPresentacionProyecto_Rev();
            db.tblPresentacionProyecto_Rev.Add(revPresentacionProyecto);
            tblProblemaInvestigacionProy_Rev revProblemaProy = new tblProblemaInvestigacionProy_Rev();
            db.tblProblemaInvestigacionProy_Rev.Add(revProblemaProy);
            tblMarcoReferenciaProy_Rev revMarcoProy = new tblMarcoReferenciaProy_Rev();
            db.tblMarcoReferenciaProy_Rev.Add(revMarcoProy);
            tblMetodoProy_Rev revMetodoProy = new tblMetodoProy_Rev();
            db.tblMetodoProy_Rev.Add(revMetodoProy);
            tblCaracteristicasProy_Rev revCaracteristicasProy = new tblCaracteristicasProy_Rev();

MAI/Views/ProyectosInvestigacion/CrearProyecto.cshtml
@model MAI.Models.DataBase.tblGruposInvestigacion

@{
    ViewBag.Title = "Nuevo Proyecto";
}

<div class="grid fluid">
    @using (Html.BeginForm("CrearProyecto", "ProyectosInvestigacion"))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("tblGruposInvestigacion_ID", Model.tblGruposInvestigacion_ID)

        <div class="row">
            <h2><strong>Nuevo Proyecto</strong></h2>
            <div class="input-control text">
                @Html.TextBox("proyInv_nombreProyecto", null, new { placeholder = "Nombre del Proyecto" })
                <button type="button" class="btn btn-clear" tabindex="-1"></button>
                @Html.ValidationMessage("Digite el nombre de su nuevo proyecto")
            </div>
        </div>

        <div class="row">
            <button class="large bg-green fg-white" type="submit">
                Crear Proyecto
                <i class="icon-plus bg-green fg-white"></i>
            </button>
        </div>
    }
</div>

MAI/Views/ProyectosInvestigacion/Create.cshtml
@model MAI.Models.DataBase.tblFechaCronograma

@{
    ViewBag.Title = "Create";
}

<div class="row">
    @using (Html.BeginForm("Create", "FechasCronograma"))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("tblCronogramaProy_ID", Model.tblCronogramaProy_ID)

        <div class="row">
            <div class="span2">
                <strong>Actividad</strong>
            </div>
            <div class="span10 input-control text">
                @Html.EditorFor(m => m.cro_Actividad)
                @Html.ValidationMessage("¿Que actividad va a realizar?")
            </div>
        </div>
        <div class="row">
            <div class="span2">
                <strong>Fecha Inicio</strong>
            </div>
            <div class="span4 input-control text" data-role="datepicker" data-format="dd/mm/yyyy" style='max-width: 130px'>
                @Html.TextBoxFor(m => m.cro_FechaInicio, "{0:dd/MM/yyyy}")
                <button class="btn btn-date" type="button"></button>
                @Html.ValidationMessage("Digite fecha de inicio")
            </div>
            <div class="span2">
                <strong>Fecha Final</strong>
            </div>
            <div class="span4 input-control text" data-role="datepicker" data-format="dd/mm/yyyy" style='max-width: 130px'>
                @Html.TextBoxFor(m => m.cro_FechaFin, "{0:dd/MM/yyyy}")
                <button class="btn btn-date" type="button"></button>
                @Html.ValidationMessage("Digite fecha de inicio")
            </div>
        </div>
        <div class="row">
            <div class="span2">
                <strong>Indicador</strong>
            </div>
            <div class="span10 input-control text">
                @Html.EditorFor(m => m.cro_Indicador)
                @Html.ValidationMessage("Indicador")
            </div>
        </div>
        <div class="row">
            <button class="large bg-green fg-white" type="submit">
                Agregar Fecha
                <i class="icon-plus bg-green fg-white"></i>
            </button>
        </div>
    }
</div>

@section Scripts{
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.min-1.11.1.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

MAI/Views/ProyectosInvestigacion/EditarProyecto.cshtml
@model MAI.Models.DataBase.tblProyectosInvestigacion

@using MAI.Models.DataBase

@{
    ViewBag.Title = "EditarProyecto";
}

<div class="grid fluid">

    <div id="informeProyectoDialog">
    </div>
    <button id="lnkInformeProyecto" type="button" class="large bg-green fg-white"
            onclick="javascript: FinalizarProyecto(@Model.tblProyectosInvestigacion_ID);">
        Ver Informe
        <i class="icon-plus bg-gren fg-white"></i>
    </button>

    @{
        investicEntities db = new investicEntities();
        var grupoInvestigacion = db.tblGruposInvestigacion.Find(Model.tblGruposInvestigacion_ID);
        @Html.Partial("~/Views/Shared/_GrupoInvestigacion.cshtml", grupoInvestigacion);

    }

    <h1>Complete su proyecto</h1>

    @Html.Partial("~/Views/Shared/_ProyectoInvestigacion.cshtml", Model)

    <div id="wizard" data-id="@Model.tblProyectosInvestigacion_ID">
        @*Hoja 1 del wizard*@
        <h1>PRESENTACIÓN DEL PROYECTO</h1>
        <div class="overflow">
            @Html.Partial("~/Views/PresentacionProyecto/Edit.cshtml", Model)
        </div>


        @*Hoja 2 del wizard*@
        <h1>PROBLEMA DE INVESTIGACIÓN</h1>
        <div class="overflow">
            @Html.Partial("~/views/ProblemaInvestigacionProy/Edit.cshtml", Model)
        </div>

        @*Hoja 3 del wizard*@
        <h1>MARCO DE REFERENCIA</h1>
        <div class="overflow">
            @Html.Partial("~/Views/MarcoReferenciaProy/Edit.cshtml", Model)
        </div>

        @*Hoja 4 del wizard*@
        <h1>MÉTODO</h1>
        <div class="overflow">
            @Html.Partial("~/Views/MetodoProy/Edit.cshtml", Model)
        </div>

        @*Hoja 5 del wizard*@
        <h1>CARACTERISTICAS</h1>
        <div class="overflow">
            @Html.Partial("~/Views/CaracteristicasProy/Edit.cshtml", Model)
        </div>

        @*Hoja 6 del wizard*@
        @*<h1>ASPECTOS ADMINISTRATIVOS</h1>
            <div class="overflow">

            </div>*@

        @*Hoja 6 CRONOGRAMA*@
        <h1>CRONOGRAMA</h1>
        <div class="overflow">
            @Html.Partial("~/Views/CronogramaProy/Edit.cshtml", Model.tblCronogramaProy)
        </div>

        @*Hoja 7 PRESUPUESTO*@
        <h1>PRESUPUESTO</h1>
        <div class="overflow">
            Presupuesto
        </div>


        @*Hoja 8 del wizard*@
        <h1>REFERENCIAS</h1>
        <div class="overflow">
            @Html.Partial("~/Views/ReferenciasProy/Edit.cshtml", Model)
        </div>
    </div>


    <div class="form-group">
        <h3>
            @Html.ActionLink("Regresar", "DetallesGrupo", "GruposInvestigacion", new { id = Model.tblGruposInvestigacion_ID }, null)
        </h3>
    </div>

</div>

@*<div id="informacion-proyecto">
        @{
            tblProyectosInvestigacion miProyectoTerminado = db.tblProyectosInvestigacion.Find(Model.tblProyectosInvestigacion_ID);
            Html.RenderPartial("InformeProyecto", miProyectoTerminado);
        }
    </div>*@

<div id="addFechaDialog">
    @{
        tblFechaCronograma miNuevaFecha = new tblFechaCronograma();
        miNuevaFecha.tblCronogramaProy_ID = Model.tblCronogramaProy_ID;
        //Html.Partial("~/Views/FechasCronograma/Create.cshtml", miNuevaFecha);
        //Html.RenderPartial("~/Views/FechasCronograma/Create.cshtml", miNuevaFecha);
        Html.RenderPartial("Create", miNuevaFecha);
        //Html.RenderAction("Create", "FechasCronograma", new { id = Model.tblCronogramaProy_ID });
    }
</div>




@section Scripts {
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.min-1.11.1.js"></script>
    <script src="~/Scripts/DataTables-1.10.3/media/js/jquery.dataTables.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.steps.js"></script>
    <link href="~/Content/Investic/jquery.steps.css" rel="stylesheet" />
    <script src="~/Scripts/Investic/mai_WizardProyectos.js"></script>
    @*<script src="~/Scripts/Investic/FechaCronograma.js"></script>*@
    <script src="~/Scripts/Investic/mai_AddIntegranteGrupoInv.js"></script>
    <script src="~/Scripts/Investic/mai_InformeProyecto.js"></script>
    <script src="~/Scripts/Investic/mai_MEpistemologicoCascading.js"></script>

}



MAI/Views/ProyectosInvestigacion/Index.cshtml
@model IEnumerable<MAI.Models.DataBase.tblProyectosInvestigacion>

<div class="row">
    <table id="miTabla" class="table striped hover">
        <thead>
            <tr>
                <th class="span2"></th>
                <th class="span5">Nombre del Proyecto</th>
                <th class="span5">Resumen</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @if (item.tblEstado_ID == 1)
                    {
                        <td>@Html.ActionLink("Modificar Proyecto", "EditarProyecto", "ProyectosInvestigacion", new { id = item.tblProyectosInvestigacion_ID }, new { @class = "button info" })</td>
                    }
                    else
                    {
                        <td>Proyecto en Evaluación</td>
                    }
                    <td>@Html.DisplayFor(model => item.tblPresentacionProyecto.preProy_tituloProy)</td>
                    <td>@Html.DisplayFor(model => item.tblPresentacionProyecto.preProy_resumenProy)</td>
                </tr>
            }
        </tbody>

    </table>
</div>

@section Scripts{
    <script src="~/Scripts/DataTables-1.10.3/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/Investic/mai_MisTablas.js"></script>
}

MAI/Views/ProyectosInvestigacion/InformeProyecto.cshtml
@model MAI.Models.DataBase.tblProyectosInvestigacion
@{
    Layout = null;
}

<div class="grid fluid" id="top">
    <div class="row">
        @*Encabezado*@
    </div>

    @*Desplegar Proyecto*@
    @Html.Partial("~/Views/Shared/_InformeProyecto.cshtml", Model)


    <div class="row padding20 bg-grayLighter">
        <p>
            Se ha finalizado la Edición de su propuesta de Proyecto denominado<br />
            <strong>@Html.DisplayFor(m => m.tblPresentacionProyecto.preProy_tituloProy)</strong>.<br />
            Asegúrese que todos los campos fueron diligenciados correctamente para que sus ideas sean tomadas en cuenta.<br />
            Si lo considera conveniente edite toda la información suministrada hasta que sea de su agrado;<br />
            si aún existen modificaciones <strong>cancele este paso</strong>.<br /><br />
            ¿Desea que esta propuesta sea revisada por el grupo de Evaluadores Investic y Colciencias?<br /><br />

            <a href="/ProyectosInvestigacion/PromoverProyecto?id=@Model.tblProyectosInvestigacion_ID" class="button bg-green fg-white">
                Agregar
                <i class="icon-upload-3 bg-green fg-white"></i>
            </a>
            @Html.ActionLink("Cancelar", "DetallesGrupo", "GruposInvestigacion", new { id = Model.tblGruposInvestigacion_ID }, new { @class = "button danger large" })


            @*@using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("tblProyectosInvestigacion_ID", Model.tblProyectosInvestigacion_ID)
                    <a href="/ProyectosInvestigacion/PromoverProyecto?id=@Model.tblProyectosInvestigacion_ID" class="button bg-green fg-white">
                        Agregar
                        <i class="icon-plus bg-green fg-white"></i>
                    </a>



                    <button class="large bg-green fg-white" type="submit">
                        Evaluar Proyecto
                        <i class="icon-upload-3 bg-green fg-white"></i>
                    </button>
                    @Html.ActionLink("Cancelar", "DetallesGrupo", "GruposInvestigacion", new { id = Model.tblGruposInvestigacion_ID }, new { @class = "button danger large" })

                }*@
        </p>
    </div>
</div>

MAI/Views/ProyectosInvestigacion/Proyectos.cshtml
@model MAI.Models.DataBase.tblGruposInvestigacion

@{
    ViewBag.Title = "Proyectos";
}

<div class="grid fluid">
    <div class="row">
        @Html.Partial("~/Views/Shared/_GrupoInvestigacion.cshtml", Model)
        <div class="row">
            <button id="AddNuevoProyecto" type="button" class="large bg-green fg-white">
                Crear Nuevo Proyecto
                <i class="icon-plus bg-green fg-white"></i>
            </button>
        </div>

        <h2>Nuestros Proyectos</h2>

        <table id="miTabla" class="table striped hover">
            <thead>
                <tr>
                    <th class="span4">Nombre del Proyecto</th>
                    <th class="span4">Resumen</th>
                    <th class="span2">Fecha de Creación</th>
                    <th class="span2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.tblProyectosInvestigacion)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => item.proyInv_nombreProyecto)</td>
                        <td>@Html.DisplayFor(model => item.tblPresentacionProyecto.preProy_resumenProy)</td>
                        <td class="text-center">@Html.DisplayFor(model => item.proyInv_fechaCreacion)</td>
                        @if (item.tblEstado_ID == 1)
                        {
                            <td class="text-center">
                                @Html.ActionLink("Modificar Proyecto", "EditarProyecto", "ProyectosInvestigacion", new { id = item.tblProyectosInvestigacion_ID }, new { @class = "button info" })
                                <input id="deleteProyecto" type="button" value="Eliminar Proyecto" onclick="location.href='@Url.Action("EliminarProyecto", "ProyectosInvestigacion", new { id = item.tblProyectosInvestigacion_ID })'" />
                            </td>
                        }
                        else
                        {
                            <td class="text-center">Proyecto en Evaluación</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="form-group">
        <h3>
            @Html.ActionLink("Regresar", "DetallesGrupo", "GruposInvestigacion", new { id = Model.tblGruposInvestigacion_ID }, null)
        </h3>
    </div>
</div>

<div id="crearProyectoDialog">
    @{
        Html.RenderPartial("CrearProyecto", Model);
    }
</div>

@section Scripts{
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.min-1.11.1.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/DataTables-1.10.3/media/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/Investic/mai_MisTablas.js"></script>
    <script src="~/Scripts/Investic/mai_ProyectosInvestigacion.js"></script>
}